name: Build when push
on: push
jobs:
  build:
    name: Build of project example
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build
      - name: project deploy
        run: echo "Deploying to production..."
        