name: Démo outputs
run-name: "Exécution du workflow ${{github.workflow}} pour le commit ${{github.event.head_commit.message}}" 
on: push
jobs:
  job1: 
    runs-on: ubuntu-latest
    outputs:
      sortie1: "valeur de la sortie 1"
      sortie2: "valeur de la deuxième sortie"
    steps:
      - id: etape1
        name: Set VAR1
        run: echo "VAR1=Hello"  >> $GITHUB_OUTPUT
      - id: etape2
        name: Set VAR2
        run: echo "VAR2=World"   >> $GITHUB_OUTPUT
      - id: etape3
        name: echo VAR1 VAR2
        run: echo ${{ steps.etape1.outputs.VAR1 }} ${{ steps.etape2.outputs.VAR2 }}
  job2:
    name: Récupère les paramètres de job1
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: echo sortie 1 sortie 2
        run: echo ${{job1.outputs.sortie1}} ${{job1.outputs.sortie2}}