name: workflow on issue creation
on: 
  issues:
    types: 
      - opened

jobs: 
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE_URL --body "Thanks for opening this issue"
        env:
          GH_TOKEN: ${{ secret.GITHUB_TOKEN }}
          ISSUE_URL:  ${{ github.event.issue.html_url }}
  output: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nouvelle issue - ${{ github.event.issue.title }}"