name: WorkFlow issue
on:
  issues:
    types:
      - opened

jobs:
  commentaire:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE_URL --body "Merci d'avoir ouvert cette issue !"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
  output:
    runs-on: ubutun-latest
    steps:
      - run: echo Nouvelle issue ${{ github.event.issue.title }}